import Head from 'next/head'

import Partida from 'components/Partida'

import shuffle from "utils/shuffle"

export default function Home() {
  const bolasJugando = shuffle()


  return (
    <>
      <Head>
        <title>Mae Mía</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Partida bolasJugando={bolasJugando} />

    </>
  )
}
