import Head from 'next/head'

import Sorteo from 'components/Sorteo/index'
export default function PSorteo() {

    return (
        <>
            <Head>
                <title>Mae Mía</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Sorteo />

        </>
    )
}
